# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panalyze_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_power_logger_gui(object):
    def setupUi(self, power_logger_gui):
        power_logger_gui.setObjectName("power_logger_gui")
        power_logger_gui.resize(675, 569)
        self.centralwidget = QtWidgets.QWidget(power_logger_gui)
        self.centralwidget.setObjectName("centralwidget")
        self.plotview_V = PlotWidget(self.centralwidget)
        self.plotview_V.setGeometry(QtCore.QRect(195, 10, 471, 181))
        self.plotview_V.setObjectName("plotview_V")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 181, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblport = QtWidgets.QLabel(self.frame)
        self.lblport.setGeometry(QtCore.QRect(9, 31, 31, 16))
        self.lblport.setObjectName("lblport")
        self.lblbaudrate = QtWidgets.QLabel(self.frame)
        self.lblbaudrate.setGeometry(QtCore.QRect(9, 61, 58, 14))
        self.lblbaudrate.setObjectName("lblbaudrate")
        self.txtbaudrate = QtWidgets.QLineEdit(self.frame)
        self.txtbaudrate.setGeometry(QtCore.QRect(69, 59, 101, 20))
        self.txtbaudrate.setObjectName("txtbaudrate")
        self.cboportlist = QtWidgets.QComboBox(self.frame)
        self.cboportlist.setGeometry(QtCore.QRect(69, 29, 101, 24))
        self.cboportlist.setObjectName("cboportlist")
        self.bttnrefreshports = QtWidgets.QPushButton(self.frame)
        self.bttnrefreshports.setGeometry(QtCore.QRect(70, 6, 88, 21))
        self.bttnrefreshports.setObjectName("bttnrefreshports")
        self.bttnconnect = QtWidgets.QPushButton(self.frame)
        self.bttnconnect.setGeometry(QtCore.QRect(10, 80, 88, 27))
        self.bttnconnect.setObjectName("bttnconnect")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 140, 181, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.rdoma = QtWidgets.QRadioButton(self.frame_3)
        self.rdoma.setGeometry(QtCore.QRect(5, 17, 51, 21))
        self.rdoma.setChecked(True)
        self.rdoma.setObjectName("rdoma")
        self.rdoa = QtWidgets.QRadioButton(self.frame_3)
        self.rdoa.setGeometry(QtCore.QRect(54, 17, 41, 21))
        self.rdoa.setObjectName("rdoa")
        self.lblcunit = QtWidgets.QLabel(self.frame_3)
        self.lblcunit.setGeometry(QtCore.QRect(10, 0, 58, 14))
        self.lblcunit.setObjectName("lblcunit")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 60, 161, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lblpunit = QtWidgets.QLabel(self.frame_4)
        self.lblpunit.setGeometry(QtCore.QRect(10, 0, 58, 14))
        self.lblpunit.setObjectName("lblpunit")
        self.rdomw = QtWidgets.QRadioButton(self.frame_4)
        self.rdomw.setGeometry(QtCore.QRect(7, 16, 51, 21))
        self.rdomw.setChecked(True)
        self.rdomw.setObjectName("rdomw")
        self.rdow = QtWidgets.QRadioButton(self.frame_4)
        self.rdow.setGeometry(QtCore.QRect(66, 16, 51, 21))
        self.rdow.setObjectName("rdow")
        self.plotview_C = PlotWidget(self.centralwidget)
        self.plotview_C.setGeometry(QtCore.QRect(194, 195, 471, 181))
        self.plotview_C.setObjectName("plotview_C")
        self.plotview_P = PlotWidget(self.centralwidget)
        self.plotview_P.setGeometry(QtCore.QRect(195, 380, 471, 181))
        self.plotview_P.setObjectName("plotview_P")
        power_logger_gui.setCentralWidget(self.centralwidget)

        self.retranslateUi(power_logger_gui)
        QtCore.QMetaObject.connectSlotsByName(power_logger_gui)

    def retranslateUi(self, power_logger_gui):
        _translate = QtCore.QCoreApplication.translate
        power_logger_gui.setWindowTitle(_translate("power_logger_gui", "Power Logger"))
        self.lblport.setText(_translate("power_logger_gui", "Port"))
        self.lblbaudrate.setText(_translate("power_logger_gui", "Baudrate"))
        self.txtbaudrate.setText(_translate("power_logger_gui", "9600"))
        self.bttnrefreshports.setText(_translate("power_logger_gui", "Refresh Ports"))
        self.bttnconnect.setText(_translate("power_logger_gui", "Connect"))
        self.rdoma.setText(_translate("power_logger_gui", "mA"))
        self.rdoa.setText(_translate("power_logger_gui", "A"))
        self.lblcunit.setText(_translate("power_logger_gui", "Current:"))
        self.lblpunit.setText(_translate("power_logger_gui", "Power:"))
        self.rdomw.setText(_translate("power_logger_gui", "mW"))
        self.rdow.setText(_translate("power_logger_gui", "W"))

from pyqtgraph import PlotWidget
